trigger:
- main

variables:
  tag: '$(Build.BuildId)'

resources:
  repositories:
    - repository: self
    - repository: githubRepo
      type: github
      endpoint: 'mai-efat'  # ✅ Update this
      name: 'mai-efat/PHP'
      ref: main

stages:
- stage: Build
  displayName: Build Docker Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/product/Dockerfile'
        tags: |
          $(tag)

 - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)

    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        Dockerfile: '$(Build.SourcesDirectory)/product/Dockerfile'  # Adjust path if needed
        tags: |
          $(imageName):$(tag)
          $(imageName):$(Build.BuildId)

    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: push
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageName)
        tags: |
          $(tag)
          $(Build.BuildId)

    - script: echo "✅ Docker image pushed to Docker Hub"
      displayName: Confirm Push

