trigger:
- main

variables:
  pythonVersion: '3.10'
  artifactFeed: 'python-packages'  # Azure Artifacts feed name

stages:
- stage: Build
  displayName: Build and Publish Python Package
  jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self

        # Set up Python
        - task: UsePythonVersion@0
          inputs:
            version: $(pythonVersion)

        # Install dependencies from product directory
        - script: |
            python -m pip install --upgrade pip setuptools wheel twine
            pip install -r product/requirements.txt
          displayName: Install dependencies

        # Build the package
        - script: |
            cd product
            chmod +x product/api.py

            python api.py sdist bdist_wheel
          displayName: Build Python package

        # Publish to Azure Artifacts
        - script: |
            pip install twine
            twine upload --repository-url https://pkgs.dev.azure.com/YOURORG/YOURPROJECT/_packaging/$(artifactFeed)/pypi/upload dist/*
          displayName: Publish to Azure Artifacts
          env:
            TWINE_USERNAME: $(System.AccessToken)
            TWINE_PASSWORD: $(System.AccessToken)
