trigger:
- main

resources:
  repositories:
    - repository: self
    - repository: githubRepo
      type: github
      endpoint: 'Your-GitHub-Service-Connection'
      name: 'mai-efat/PHP'
      ref: main  # Change if needed

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Docker Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self  # Ensures pipeline checks out the correct repo
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
