trigger:
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    downloadPath: '$(System.ArtifactsDirectory)'
- main

variables:
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: 'docker'
  imageName: 'maieffat/php'

resources:
  repositories:
    - repository: self
    - repository: githubRepo
      type: github
      endpoint: 'mai-efat'
      name: 'mai-efat/PHP'
      ref: main

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
    - job: Build
      displayName: Build Docker Image
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self

        - task: Docker@2
          displayName: Build Docker Image
          inputs:
            command: build
            Dockerfile: '$(Build.SourcesDirectory)/product/Dockerfile'
            repository: $(imageName)
            tags: $(tag)

        - script: |
            mkdir -p $(Build.ArtifactStagingDirectory)
            docker save -o $(Build.ArtifactStagingDirectory)/docker-image.tar $(imageName):$(tag) || {
              echo "❌ Docker image save failed." > /home/vsts/work/_temp/task_outputs/build_1739631147052.txt
              exit 1
            }
          displayName: Save Docker Image as TAR

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)/docker-image.tar'
            artifactName: 'docker-image'
          displayName: Publish Docker Image Artifact

        - script: |
            echo "✅ Docker image $(imageName):$(tag) saved to artifacts" > /home/vsts/work/_temp/task_outputs/build_1739631147052.txt
          displayName: Confirm Artifact Upload
