trigger:
- main

variables:
  tag: '$(Build.BuildId)'

resources:
  repositories:
    - repository: self
    - repository: githubRepo
      type: github
      endpoint: 'mai-effat'  # ✅ Update this
      name: 'mai-efat/PHP'
      ref: main

stages:
- stage: Build
  displayName: Build Docker Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self  # ✅ Ensure it checks out the repo
      persistCredentials: true
    - script: echo "Pipeline is running correctly!"  # ✅ Debugging step
      displayName: "Debugging Step"
    - script: ls -l $(Build.SourcesDirectory)  # ✅ Debugging step to check files
      displayName: "List Source Directory"
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/product/Dockerfile'  # ✅ Update if needed
        tags: |
          $(tag)
