trigger:
- main

variables:
  tag: '$(Build.BuildId)'

resources:
  repositories:
    - repository: self
    - repository: githubRepo
      type: github
      endpoint: 'mai-efat'  # ✅ Update this
      name: 'mai-efat/PHP'
      ref: main

stages:
- stage: Build
  displayName: Build Docker Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/product/Dockerfile'
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy Application
  dependsOn: Build  # Ensures this stage runs AFTER Build
  jobs:
  - job: Deploy
    displayName: Deploy Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo "Deploying application..."

